### ISSUE TITLE
Deployment support

### ISSUE THREAD

**Issue by friedrichg** [aws/zone-aware-controllers-for-k8s#4]
Deployments could definitely benefit from ZoneAwareUpdate

For example:

```
apiVersion: zonecontrol.k8s.aws/v1
kind: ZoneAwareUpdate
metadata:
  name: <zau-name>
spec:
  deployment: <deployment-name>
  maxUnavailable: 2
```
